SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME from ANIMAL_INS INS 
LEFT OUTER JOIN ANIMAL_OUTS OUTS 
on INS.ANIMAL_ID = OUTS.ANIMAL_ID
where INS.SEX_UPON_INTAKE != OUTS.SEX_UPON_OUTCOME
order by INS.ANIMAL_ID